horspeed = random_range(-1.2, 1.2);
verspeed = random_range(-1.2, -2);
sprite_index = choose(meatchunk_spr, meatchunk2_spr);
image_speed = 0;
image_angle = random_range(0, 359);
image_xscale = choose(random_range(0.8, 1), random_range(-0.8, -1));
image_yscale = choose(random_range(0.8, 1), random_range(-0.8, -1));
gravityStrength = -0.058;
destroyTimer = 1620;
